image.upload.dir=/var/lib/tomcat10/uploads
test-data.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/artificial_news
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect