spring.application.name=artificial-news
spring.ai.openai.api-key=${API_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/artificial_news
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=prod
# Override with ./gradlew bootRun --args='--spring.profiles.active=dev'
# or
# spring.profiles.active=dev

